### ISSUE TITLE
Listeners

### ISSUE THREAD

**Issue by oghmios** [cgkineo/adapt-component-animate#1]
Hi, I wanna put a listener (listenTo) in that plugin in js file, where is the best place to put it? Is better create a new function to the listeners or include it in another function?

Thank you for all

**Comment by oliverfoster** [comment]
listenTo is part of an observer:observable relationship whereby the observer listens to the observable. in this extension the Adapt global object is the observable but there is no observer object with which to listenTo from. For most other extensions or components there is a View object which becomes the observer of another, that is not the case in this instance. You will have to either re-write this extension to provide an observer object (a Backbone Model, View or ``_.extend({}, Backbone.Events);`` object) or find an alternative way of doing this. i.e. ``Adapt.on("eventName", function() {});``
